In [1]:
from numpy import *
import time
def trad_version():
    t1=time.time()
    X=range(10000000)
    Y=range(10000000)
    Z=[]
    for i in range (len(X)):
        Z.append(X[i]+Y[i])
    return time.time()-t1

In [2]:
trad_version()

4.82431435585022

In [7]:
def numpy_version():
    t1=time.time()
    X=arange(10000000)
    Y=arange(10000000)
    Z = X + Y
    return time.time()-t1

In [8]:
numpy_version()

0.12168717384338379

In [10]:
import numpy as np
import warnings 
warnings.filterwarnings('ignore')
from IPython.display import Image

In [11]:
#Numpy dizisi yaratmak

In [12]:
list1 = [10, 20, 30, 40, 50, 60]
list1

[10, 20, 30, 40, 50, 60]

In [13]:
type(list1)

list

In [14]:
arr1 = np.array(list1)
arr1

array([10, 20, 30, 40, 50, 60])

In [15]:
arr1.data

In [16]:
type(arr1)

numpy.ndarray

In [17]:
arr1.dtype

dtype('int32')

In [18]:
arr1.astype(float)

array([10., 20., 30., 40., 50., 60.])

In [19]:
#arange

In [20]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
np.arange(0, 100, 10)

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [22]:
np.arange(100, 10, -10)

array([100,  90,  80,  70,  60,  50,  40,  30,  20])

In [23]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [24]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [25]:
np.repeat(10, 5)

array([10, 10, 10, 10, 10])

In [26]:
a = np.array([10,20,30])
np.repeat(a, 3)

array([10, 10, 10, 20, 20, 20, 30, 30, 30])

In [27]:
np.full(5, 10)

array([10, 10, 10, 10, 10])

In [28]:
#Tek/çift sayı yazdırma

In [29]:
ar1 = np.arange(1, 20)
ar1[ar1 % 2 == 1]

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [31]:
ar1 = np.arange(0, 20)
ar1[ar1 % 2 == 0]

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [32]:
np.linspace(10, 20, 4)

array([10.        , 13.33333333, 16.66666667, 20.        ])

In [33]:
np.linspace(10, 20, 11)

array([10., 11., 12., 13., 14., 15., 16., 17., 18., 19., 20.])

In [34]:
#Random

In [35]:
np.random.random(4)

array([0.87514462, 0.91571133, 0.83243022, 0.25499539])

In [36]:
np.random.randint(0, 500, 5)

array([ 59, 480, 407,  10, 474])

In [37]:
np.random.randint(0, 500, 10)

array([168, 403, 182, 125,  39,   6, 164, 215, 487,  69])

In [38]:
#seed (çekirdek)

In [39]:
np.random.seed(123)
np.random.randint(0, 100, 10)

array([66, 92, 98, 17, 83, 57, 86, 97, 96, 47])

In [40]:
np.random.seed(123)
np.random.randint(0, 100, 10)

array([66, 92, 98, 17, 83, 57, 86, 97, 96, 47])

In [41]:
np.random.seed(101)
np.random.randint(0, 100, 10)

array([95, 11, 81, 70, 63, 87, 75,  9, 77, 40])

In [42]:
f1 = np.random.uniform(5, 10, size = (10))
f1

array([6.5348311 , 9.4680654 , 8.60771931, 5.94969477, 7.77113796,
       6.76065977, 5.90946201, 8.92800881, 9.82741611, 6.16176831])

In [43]:
np.floor(f1)

array([6., 9., 8., 5., 7., 6., 5., 8., 9., 6.])

In [44]:
np.trunc(f1)

array([6., 9., 8., 5., 7., 6., 5., 8., 9., 6.])

In [45]:
f1.astype(int)

array([6, 9, 8, 5, 7, 6, 5, 8, 9, 6])

In [46]:
b2 = np.random.randn(10)
b2

array([ 0.18869531, -0.75887206, -0.93323722,  0.95505651,  0.19079432,
        1.97875732,  2.60596728,  0.68350889,  0.30266545,  1.69372293])

In [47]:
arr1

array([10, 20, 30, 40, 50, 60])

In [48]:
for index, value in np.ndenumerate(arr1):
    print(index, value)

(0,) 10
(1,) 20
(2,) 30
(3,) 40
(4,) 50
(5,) 60


In [49]:
#Dizi üzerindeki operasyonlar

In [50]:
arr2 = np.arange(1, 20)

In [51]:
arr2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [52]:
arr2.sum()

190

In [53]:
np.cumsum(arr2)

array([  1,   3,   6,  10,  15,  21,  28,  36,  45,  55,  66,  78,  91,
       105, 120, 136, 153, 171, 190], dtype=int32)

In [54]:
arr1.min()

10

In [55]:
arr1.max()

60

In [56]:
arr2.argmin()

0

In [57]:
arr2.argmax()

18

In [58]:
arr2.mean()

10.0

In [60]:
np.median(arr2)

10.0

In [61]:
np.var(arr2)

30.0

In [62]:
np.std(arr2)

5.477225575051661

In [63]:
#Matrisler

In [64]:
A = np.array([[1,2,3,0], [5,6,7,22], [10,11,1,13], [14,15,16,3]])
A

array([[ 1,  2,  3,  0],
       [ 5,  6,  7, 22],
       [10, 11,  1, 13],
       [14, 15, 16,  3]])

In [65]:
A.sum()

129

In [66]:
#min(), max(), mean(), median(), var()

In [67]:
np.amin(A, axis = 0) #sütun bazlı minimum değer bulma

array([1, 2, 1, 0])

In [68]:
np.amin(A, axis = 1)

array([0, 5, 1, 3])

In [69]:
np.std(A)

6.348904925260734

In [70]:
for index, value in np.ndenumerate(A):
    print(index, value)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 0
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 22
(2, 0) 10
(2, 1) 11
(2, 2) 1
(2, 3) 13
(3, 0) 14
(3, 1) 15
(3, 2) 16
(3, 3) 3


In [71]:
#Elemanları okuma

In [72]:
a = np.array([7,5,3,9,0,2])

In [73]:
a[0]

7

In [74]:
a[1:]

array([5, 3, 9, 0, 2])

In [75]:
a[1:4]

array([5, 3, 9])

In [76]:
a[-1]

2

In [77]:
a[-6]

7

In [78]:
a[-3:-1]

array([9, 0])

In [79]:
#Dizideki elemanları değiştirme

In [80]:
ar = np.arange(1, 20)
ar

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [81]:
rep1 = np.where(ar % 2 == 0, 0, ar)
print(rep1)

[ 1  0  3  0  5  0  7  0  9  0 11  0 13  0 15  0 17  0 19]


In [ ]:
#where 2. örnek